export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST" ;
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS" ;
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE" ;
// Women
export const GET_WOMEN_REQUEST = "GET_WOMEN_REQUEST" ;
export const GET_WOMEN_SUCCESS = "GET_WOMEN_SUCCESS" ;
export const GET_WOMEN_FAILURE = "GET_WOMEN_FAILURE" ;
// Child
export const GET_CHILD_REQUEST = "GET_CHILD_REQUEST" ;
export const GET_CHILD_SUCCESS = "GET_CHILD_SUCCESS" ;
export const GET_CHILD_FAILURE = "GET_CHILD_FAILURE" ;